---
abstract: 'Debugger interface to many debuggers'
author:
  - 'Eric Johnson <vimdebug at iijo dot org>'
build_requires:
  English: 0
  File::Which: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: VimDebug
requires:
  Carp: 0
  Cwd: 0
  File::Basename: 0
  File::Spec: 0
  Getopt::Long: 0
  IO::Pty: 0
  IPC::Run: 0
  UNIVERSAL: 0
  perl: 5.006
  vars: 0
version: 0.5
